export const SET_AMOUNT_TO_CONVERT = 'SET_AMOUNT_TO_CONVERT';
export const SUBMIT_AMOUNT_TO_CONVERT = 'SUBMIT_AMOUNT_TO_CONVERT';
export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const LOADING_STATUS_CURRENCIES = 'LOADING_STATUS_CURRENCIES';
export const LOADING_STATUS_RESULTS = 'LOADING_STATUS_RESULTS';


