export const SET_AMOUNT_TO_CONVERT = 'SET_AMOUNT_TO_CONVERT';
export const SUBMIT_AMOUNT_TO_CONVERT = 'SUBMIT_AMOUNT_TO_CONVERT';
export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const LOADING_STATUS_CURRENCIES = 'LOADING_STATUS_CURRENCIES';
export const LOADING_STATUS_RESULTS = 'LOADING_STATUS_RESULTS';

export const GET_CURRENCY_TO_CONVERT_FROM = 'GET_CURRENCY_TO_CONVERT_FROM';
export const GET_CURRENCY_TO_CONVERT_TO = 'GET_CURRENCY_TO_CONVERT_TO';

export const SUBMIT_HISTORICAL_DATE_RATE = 'SUBMIT_HISTORICAL_DATE_RATE';
